//auth actions types
export const USER_DATA = 'USER_DATA'
export const LOGIN_USER = 'LOGIN_USER'
export const MEMBER_LOG_OUT = 'MEMBER_LOG_OUT'
export const MEMBER_REGISTER = 'MEMBER_REGISTER'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'

//validation actions types
export const EMAIL_ERROR = 'EMAIL_ERROR'
export const EMAIL_ALREADY_EXIST = 'EMAIL_ALREADY_EXIST'
export const VERIFICATION_CODE = 'VERIFICATION_CODE'
export const SPLASH_USE = 'SPLASH_USE'

//client actions types
export const GET_PROVINCES = 'GET_PROVINCES'
export const GET_DISTRICTS = 'GET_DISTRICTS'
export const VERIFICATION_CODE_MSG = 'VERIFICATION_CODE_MSG'
export const PHONE_CODE_ERROR_MSG = 'PHONE_CODE_ERROR_MSG'
export const GET_CLIENT = 'GET_CLIENT'
export const GET_CLIENT_BY_PROFESSION = 'GET_CLIENT_BY_PROFESSION'
export const REGISTER_TYPE = 'REGISTER_TYPE'
export const NIKE_NAME = 'NIKE_NAME'
export const PROFILE_PICTURE = 'PROFILE_PICTURE'
export const PROFILE_PROGRESS_CLIENT = 'PROFILE_PROGRESS_CLIENT'
export const PROFILE_PROGRESS_SIDECHAR = 'PROFILE_PROGRESS_SIDECHAR'
export const ISPHONEVERIFY = 'ISPHONEVERIFY'
export const ISPHONEVERIFYCLIENT = 'ISPHONEVERIFYCLIENT'


// Side Character Profile Edit
export const UPDATE_SIDE_CHARACTER_PROFILE = 'UPDATE_SIDE_CHARACTER_PROFILE';
export const UPDATE_SIDE_CHARACTER_PROFILE_EDIT_TAB = 'UPDATE_SIDE_CHARACTER_PROFILE_EDIT_TAB';
export const CHANGE_SIDE_CHARACTER_STATES = 'CHANGE_SIDE_CHARACTER_STATES';
export const DELETE_SIDE_CHARACTER_EXPERIENCE_BY_ID = 'DELETE_SIDE_CHARACTER_EXPERIENCE_BY_ID';
export const DELETE_SIDE_CHARACTER_PORTFOLIO_BY_ID = 'DELETE_SIDE_CHARACTER_PORTFOLIO_BY_ID';

// Side Character Profile Edit
export const UPDATE_CLIENT_PROFILE = 'UPDATE_CLIENT_PROFILE';
export const UPDATE_CLIENT_PROFILE_EDIT_TAB = 'UPDATE_CLIENT_PROFILE_EDIT_TAB';
export const CHANGE_CLIENT_STATES = 'CHANGE_CLIENT_STATES';
export const DELETE_CLIENT_EXPERIENCE_BY_ID = 'DELETE_CLIENT_EXPERIENCE_BY_ID';
export const DELETE_CLIENT_PORTFOLIO_BY_ID = 'DELETE_CLIENT_PORTFOLIO_BY_ID';


export const CLIENT_CHANGE_PROGRESS = 'CLIENT_CHANGE_PROGRESS';
export const SIDECHARECTER_CHANGE_PROGRESS = 'SIDECHARECTER_CHANGE_PROGRESS';


export const CLIENT_CLIENT_SEARCH_PROFILE = 'CLIENT_CLIENT_SEARCH_PROFILE';
export const CLIENT_SIDECHARECTER_SEARCH_PROFILE = 'CLIENT_SIDECHARECTER_SEARCH_PROFILE';
export const SIDECHARECTER_SIDECHARECTER_SEARCH_PROFILE = 'SIDECHARECTER_SIDECHARECTER_SEARCH_PROFILE';
export const SIDECHARECTER_CLIENT_SEARCH_PROFILE = 'SIDECHARECTER_CLIENT_SEARCH_PROFILE';


// Project Creation
export const PROJECTDATA = 'PROJECTDATA';
export const PROJECT_PERCENTEGE = 'PROJECT_PERCENTEGE';

// notification
export const NOTIFY_CHANGE = 'NOTIFY_CHANGE';