export { default as Header } from './header'
export { default as LoginHeader } from './LoginHeader'
export { default as Footer } from './footer'
export { default as LoginFooter } from './LoginFooter'
export { default as Giftbox } from './giftBox'
export { default as SearchCard } from './searchCard'
export { default as WorkExp } from './workExp'
export { default as HeaderTab } from './headingTab'
export { default as ProfileCardBeforeLogin } from './ProfileCardBeforeLogin'
export { default as ProjectSearchCardBeforeLogin } from './projectSearchCard'
export { default as BCoinCard } from './bCoincard'
export { default as ClientStep1 } from './client/clientStep1'
export { default as ClientStep2 } from './client/clientStep2'
export { default as ClientStep3 } from './client/clientStep3'
export { default as SideCharacterStep2 } from './sideCharacter/sideCharStep2'
export { default as LoginHeaderMobile } from './LoginHeaderForMobile'
export { default as SideCharStep1 } from './sideCharacter/sideCharStep1'
export { default as SideCharStep3 } from './sideCharacter/sideCharStep3'
export { default as ProjectCard } from './projectCard'

export { default as CommonHeader } from './CommonHeader'
export { default as AppLayout } from './AppLayout'
export { default as FullFooter } from './fullFooter'

// popup
export { default as PhoneVerifyPopup } from './popup/phoneVerifyPopup'
export { default as MakeProfilePopup } from './popup/makeProfilePopup'
export { default as MakeProjectPopUp } from './popup/makeProjectPopUp'